### ISSUE TITLE
Unable to access mysql back end

### ISSUE THREAD

**Issue by colinl** [flathub/org.gnucash.GnuCash#17]
On a system which is able to use the mysql backend ok when running a locally built gnucash 3.2 the flatpak install is unable to open or Save As a mysql database.  The option appears but when access is attempted a popup is shown saying "The server at URL mysql://root@localhost/gnucash experienced an error or encountered bad or corrupt data".

I would attach the gnucash trace file but am unable to find it (see issue #16).

**Comment by plutocrat** [comment]
Just an observation ... the mysql URL seems to be lacking a username. Might be nothing, but I'd expect to see mysql:user@hostname/databasename. Just wondering out loud if that would fix it ...

**Comment by colinl** [comment]
Sorry, typo in my original bug description, it should be mysq://root@localhost/gnucash.  It doesn't show the pwd but I would not expect it to.  I have corrected the description.  If I could find the trace file then I am sure there would be more information on what the problem is.

**Comment by fellen** [comment]
> WARN <gnc.app-utils> Could not spawn perl: Failed to execute child process “perl” (No such file or directory)

perl is only used to run finance-quote

**Comment by colinl** [comment]
Yes, I didn't think that was significant.
It would be if I wanted to use FQ of course, but that is a different issue.

**Comment by colinl** [comment]
If the address of the mysql server is entered as 127.0.0.1 rather than localhost then mysql access works ok.
Thanks to Plutocrat on the gnucash users list for working that out.
Whether this is just something that users of the flatpak have to put up with or whether this can be changed in the flatpak itself I don't know.

**Comment by colinl** [comment]
@plutocrat I don't think it is that.  I tested by monitoring DNS requests from the machine and if I try to save to mysql specifying a named server then I can see the DNS request for the server going out.

**Comment by ramcq** [comment]
The content of resolv.conf is monitored by Flatpak and updated automatically into the sandbox when it changes. So this is unlikely to be a DNS problem (otherwise nothing would work).

I think the problem is actually that MySQL internally remaps `localhost` to use the UNIX socket instead of TCP, in the belief it is somehow faster/better to use a UNIX socket rather than a TCP localhost socket (on Linux at least, this is completely false - they perform essentially identically). Access to UNIX sockets is not governed by --share=network but actually by filesystem access (apart from "abstract" UNIX sockets, which don't exist in the filesystem but just use an opaque string which looks confusingly like a filesystem path... they are basically the worst thing ever, especially for sandboxing).

So - if you use "flatpak override --filesystem=/var/run/mysqld/mysqld.sock org.gnucash.GnuCash" maybe this should allow access to the MySQL socket inside the sandbox, and then the MySQL backend will connect correctly to `localhost` when it remaps it to the UNIX socket? If that works, and MySQL backend access is common enough, it seems relatively harmless for the GnuCash flatpak to just include this socket (if it exists) into the Flatpak manifest.

**Comment by colinl** [comment]
I am afraid I am not able to test this at the moment, the machine I was using for experimenting has been commandeered for another use.

**Comment by gjanssens** [comment]
Can one of you that is using the GnuCash flatpak with mysql try to start it with the following command and then try if `localhost` works to connect to your local database ?

```
flatpak run --filesystem=host org.gnucash.GnuCash
```

**Comment by neildarlow** [comment]
Hi,
From **colinl**'s comment of August 2018 i.e.:
CRIT <gnc.backend.dbi> [GncDbiBackend::session_begin()] Unable to connect to database 'gnucash'

I read gnc.backend.dbi as being the GnuCash DBI backend. DBI is a Perl database interface and I suggest that Perl is required to access the MySQL database.

Regards,
Neil Darlow

**Comment by fellen** [comment]
> I read gnc.backend.dbi as being the GnuCash DBI backend. DBI is a Perl database interface and I suggest that Perl is required to access the MySQL database.

Huh? From http://libdbi.sourceforge.net/development.html: `Database Independent Abstraction Layer for C`.
Did you confuse it with the perls https://dbi.perl.org/?

**Comment by gjanssens** [comment]
@neildarlow As @fellen explains, gnucash doesn't need perl or perl's dbi library to work with a mysql database. GnuCash uses libdbi.

The problem described in this issue is not due to missing libraries or packages, it's an access permission issue. This is illustrated by the fact that you can access a local mysql database using '127.0.0.1', but not via 'localhost'.

I have suggested a fix above, but no one has confirmed or denied whether it works for them.

**Comment by neildarlow** [comment]
Hi,

Apologies. I did confuse the two libraries. An unfortunate coincidence in naming.

Regarding **localhost**, in most scenarios it should resolve to 127.0.0.1. Could the solution be to provide the port number in the connection URI to indicate that a TCP socket connection is desired.

mysql:user@host:port/database and, indeed, mysql:user@localhost:3306/database should be valid if MySQL is listening on all interfaces.

Regards,
Neil Darlow

**Comment by gjanssens** [comment]
@neildarlow by all means please try it out and report back the result. And while you're at it, please also test my suggestion a few comments back. I currently have no time to experiment with this myself.

**Comment by gjanssens** [comment]
Recent release of gnucash on flatpak have  the security set to "host" by default. So this issue should no longer happen.

**Comment by notshriram** [comment]
I'm running macOS Monterey, I encountered the same problem, I just created a user that uses mysql_native_password authentication and it simply worked
