### ISSUE TITLE
gnucash does not respect locale

### ISSUE THREAD

**Issue by ngiger** [flathub/org.gnucash.GnuCash#4]
I have the following locale settings

    LANG=de_CH.UTF-8
    LANGUAGE=de_CH:de

when running flatpak run org.libreoffice.LibreOffice, LibreOffice opens nicely the german interface.

Running flatpak run org.gnucash.GnuCash display everyghing in english.

But thanks for your work. On my librem laptop I do not have gnucash available via apt-get.

**Comment by gjanssens** [comment]
Based on flatpak/flatpak#526 and flatpak/flatpak#1059 I gather this may be because the locale package is only partially installed.

Can you run this command:

    flatpak update --subpath= org.gnucash.GnuCash.Locale

Afterwards my gnucash package was translated.

**Comment by gjanssens** [comment]
Well, I'm not 100% sure of the details. I had to nuke my flatpak installations locally because some combination of commands damages it irreparably :(

On the new installation the above didn't work. However running

    flatpak update --subpath= org.gnome.Platform.Locale

and maybe running

  flatpak update --subpath= org.gnucash.GnuCash.Locale

afterwards did fix it.

Note the space character between `--subpath=` and `org.gnome.Platform.Locale`. Omitting it had unpleasant side-effects on my system.

**Comment by gjanssens** [comment]
Having heard nothing back in 5 months I assume the commands above have fixed the issue.
